### ISSUE TITLE
ImportError: No module named loaders.spaces_loader

### ISSUE THREAD

**Issue by denzfarid** [siddhartham/thumbor_spaces#3]
Hellow thank you for this module , I really appreciate it, but I'm having a problem, I'm using thumbor 6.7.0

```
ImportError: No module named loaders.spaces_loader
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==6.7.0', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 143, in main
    importer = get_importer(config)
  File "/usr/lib64/python2.7/site-packages/thumbor/server.py", line 70, in get_importer
    importer.import_modules()
  File "/usr/lib64/python2.7/site-packages/thumbor/importer.py", line 53, in import_modules
    self.import_item('LOADER')
  File "/usr/lib64/python2.7/site-packages/thumbor/importer.py", line 97, in import_item
    module = self.import_class(conf_value, get_module=True)
  File "/usr/lib64/python2.7/site-packages/thumbor/importer.py", line 43, in import_class
    return import_class(name, get_module)
  File "/usr/lib64/python2.7/site-packages/thumbor/importer.py", line 19, in import_class
    module = get_module and __import__(name) or __import__(module_name)
ImportError: No module named loaders.spaces_loader
```

**Comment by denzfarid** [comment]
Update, resolve
im 
`pip uninstall thumbor_spaces 
`and 
`pip install thumbor-spaces boto3`

thank you =)

**Comment by highoncarbs** [comment]
Hey  @denzfarid , still getting the issue after installing boto3 .

**Comment by denzfarid** [comment]
> Hey @denzfarid , still getting the issue after installing boto3 .

makesure your thumbor running well before install this module sir,
you must trace log, i think you miss some package sir,

im use centos 7 and python 2.7

**Comment by highoncarbs** [comment]
@denzfarid  Everything works , Thanks for the input though
